services:
  gpt-sovits:
    image: breakstring/gpt-sovits:local
    build:
      context: .
    container_name: gpt-sovits-container
    environment:
      - is_half=False
      - is_share=False
    volumes:
      - ./output:/workspace/output
      - ./logs:/workspace/logs
      - ./SoVITS_weights:/workspace/SoVITS_weights
      - ./reference:/workspace/reference
      - ./GPT_SoVITS/pretrained_models/:/workspace/GPT_SoVITS/pretrained_models
      - ./GPT_SoVITS/text:/workspace/GPT_SoVITS/text
      - ./tools/uvr5/uvr5_weights:/workspace/tools/uvr5/uvr5_weights
      - ./tools/asr/models:/workspace/tools/asr/models 
    working_dir: /workspace
    ports:
      - "9880:9880"
      - "9871:9871"
      - "9872:9872"
      - "9873:9873"
      - "9874:9874"
    shm_size: 16G
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: unless-stopped
